title: It is not about others reading, it is about me writing
baseurl: ""
url: ""
linkedin_username: shay-elmualem
twitter_username: norbinsh
github_username:  norbinsh



markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
